INSERT INTO sistema_facturacion.empresa_permisos (codigo, nombre, modulo, descripcion) VALUES
('CLIENTES_VER', 'Ver Clientes', 'CLIENTES', 'Permite visualizar la lista y detalles de clientes'),
('CLIENTES_CREAR', 'Crear Clientes', 'CLIENTES', 'Permite registrar nuevos clientes'),
('CLIENTES_EDITAR', 'Editar Clientes', 'CLIENTES', 'Permite modificar información de clientes existentes'),
('CLIENTES_ELIMINAR', 'Eliminar Clientes', 'CLIENTES', 'Permite dar de baja o eliminar clientes'),
('CLIENTES_EXPORTAR', 'Exportar Clientes', 'CLIENTES', 'Permite descargar la base de datos de clientes'),
('PRODUCTOS_VER', 'Ver Productos', 'PRODUCTOS', 'Permite visualizar el catálogo de productos'),
('PRODUCTOS_CREAR', 'Crear Productos', 'PRODUCTOS', 'Permite registrar nuevos productos'),
('PRODUCTOS_EDITAR', 'Editar Productos', 'PRODUCTOS', 'Permite modificar productos existentes'),
('PRODUCTOS_ELIMINAR', 'Eliminar Productos', 'PRODUCTOS', 'Permite eliminar productos del catálogo'),
('PRODUCTOS_VER_COSTOS', 'Ver Costos de Productos', 'PRODUCTOS', 'Permite visualizar los precios de costo'),
('FACTURAS_VER_TODAS', 'Ver Todas las Facturas', 'FACTURAS', 'Permite ver facturas de todos los usuarios'),
('FACTURAS_VER_PROPIAS', 'Ver Facturas Propias', 'FACTURAS', 'Solo permite ver facturas emitidas por el usuario'),
('FACTURAS_CREAR', 'Crear Facturas', 'FACTURAS', 'Permite la emisión de nuevas facturas'),
('FACTURAS_EDITAR', 'Editar Facturas', 'FACTURAS', 'Permite modificar borradores o datos permitidos'),
('FACTURAS_ANULAR', 'Anular Facturas', 'FACTURAS', 'Permite anular facturas emitidas'),
('FACTURAS_ENVIAR_SRI', 'Enviar al SRI', 'FACTURAS', 'Permite autorizar comprobantes electrónicos'),
('FACTURAS_DESCARGAR_PDF', 'Descargar PDF', 'FACTURAS', 'Permite descargar el RIDE de las facturas'),
('FACTURAS_ENVIAR_EMAIL', 'Enviar por Email', 'FACTURAS', 'Permite enviar facturas a los clientes por correo'),
('REPORTES_VER', 'Ver Reportes', 'REPORTES', 'Acceso general al módulo de reportes'),
('REPORTES_GENERAR', 'Generar Reportes', 'REPORTES', 'Permite procesar nuevos reportes de datos'),
('REPORTES_EXPORTAR', 'Exportar Reportes', 'REPORTES', 'Permite descargar reportes en Excel/PDF'),
('CONFIG_EMPRESA', 'Configurar Empresa', 'CONFIGURACION', 'Gestión de datos de la empresa y logo'),
('CONFIG_SRI', 'Configurar SRI', 'CONFIGURACION', 'Gestión de firma electrónica y ambiente'),
('CONFIG_MODULOS', 'Configurar Módulos', 'CONFIGURACION', 'Activar/Desactivar funcionalidades de la empresa'),
('MODULOS_GESTIONAR', 'Gestionar Módulos Empresa', 'CONFIGURACION', 'Administrar visibilidad de módulos'),
('USUARIOS_EMPRESA_VER', 'Ver Usuarios', 'USUARIOS_EMPRESA', 'Ver lista de usuarios de la empresa'),
('USUARIOS_EMPRESA_CREAR', 'Crear Usuarios', 'USUARIOS_EMPRESA', 'Registrar nuevos empleados/usuarios'),
('USUARIOS_EMPRESA_EDITAR', 'Editar Usuarios', 'USUARIOS_EMPRESA', 'Actualizar perfiles de usuario'),
('USUARIOS_EMPRESA_ELIMINAR', 'Eliminar Usuarios', 'USUARIOS_EMPRESA', 'Dar de baja usuarios de la empresa'),
('USUARIOS_VER', 'Ver Perfiles', 'USUARIOS_EMPRESA', 'Acceso a visualización de perfiles'),
('USUARIOS_GESTIONAR', 'Gestionar Usuarios', 'USUARIOS_EMPRESA', 'Administración avanzada de usuarios'),
('ROLES_VER', 'Ver Roles', 'ROLES', 'Visualizar roles configurados'),
('ROLES_CREAR', 'Crear Roles', 'ROLES', 'Definir nuevos perfiles de acceso'),
('ROLES_EDITAR', 'Editar Roles', 'ROLES', 'Modificar permisos de roles existentes'),
('ROLES_ELIMINAR', 'Eliminar Roles', 'ROLES', 'Eliminar roles de la empresa'),
('CONFIG_ROLES', 'Gestionar Permisos de Roles', 'ROLES', 'Asignar permisos específicos a roles'),
('ESTABLECIMIENTO_VER', 'Ver Establecimientos', 'ESTABLECIMIENTOS', 'Ver lista de establecimientos/sucursales'),
('ESTABLECIMIENTO_GESTIONAR', 'Gestionar Establecimientos', 'ESTABLECIMIENTOS', 'Crear/Editar/Eliminar sucursales'),
('PUNTO_EMISION_VER', 'Ver Puntos de Emisión', 'ESTABLECIMIENTOS', 'Ver lista de cajas o puntos de venta'),
('PUNTO_EMISION_GESTIONAR', 'Gestionar Puntos de Emisión', 'ESTABLECIMIENTOS', 'Administrar cajas y secuenciales'),
('PROVEEDOR_VER', 'Ver Proveedores', 'PROVEEDORES', 'Ver directorio de proveedores'),
('PROVEEDOR_CREAR', 'Crear Proveedores', 'PROVEEDORES', 'Registrar nuevos proveedores'),
('PROVEEDOR_EDITAR', 'Editar Proveedores', 'PROVEEDORES', 'Actualizar datos de proveedores'),
('PROVEEDOR_ELIMINAR', 'Eliminar Proveedores', 'PROVEEDORES', 'Eliminar proveedores del sistema'),
('GASTOS_VER', 'Ver Gastos', 'GASTOS', 'Visualizar egresos y facturas de compra'),
('GASTOS_CREAR', 'Crear Gastos', 'GASTOS', 'Registrar nuevos gastos y compras'),
('GASTOS_EDITAR', 'Editar Gastos', 'GASTOS', 'Modificar registros de egresos'),
('GASTOS_ELIMINAR', 'Eliminar Gastos', 'GASTOS', 'Anular o eliminar egresos'),
('CATEGORIA_GASTO_VER', 'Ver Categorías de Gasto', 'GASTOS', 'Ver clasificación de egresos'),
('CATEGORIA_GASTO_CREAR', 'Crear Categorías', 'GASTOS', 'Definir nuevas categorías de gasto'),
('CATEGORIA_GASTO_EDITAR', 'Editar Categorías', 'GASTOS', 'Modificar nombres de categorías'),
('CATEGORIA_GASTO_ELIMINAR', 'Eliminar Categorías', 'GASTOS', 'Limpiar catálogo de categorías'),
('PAGO_GASTO_VER', 'Ver Pagos de Gastos', 'GASTOS', 'Ver comprobantes de pago a proveedores'),
('PAGO_GASTO_CREAR', 'Pagar Gastos', 'GASTOS', 'Registrar pagos de facturas de compra'),
('PAGO_GASTO_EDITAR', 'Editar Pagos de Gasto', 'GASTOS', 'Corregir registros de pago'),
('PAGO_GASTO_ELIMINAR', 'Eliminar Pagos de Gasto', 'GASTOS', 'Anular pagos a proveedores'),
('INVENTARIO_VER', 'Ver Inventario', 'INVENTARIOS', 'Visualizar stock y movimientos'),
('INVENTARIO_CREAR', 'Cargar Inventario', 'INVENTARIOS', 'Registrar ingresos/egresos de stock'),
('INVENTARIO_EDITAR', 'Ajustar Inventario', 'INVENTARIOS', 'Realizar ajustes manuales de stock'),
('INVENTARIO_ELIMINAR', 'Eliminar Movimientos', 'INVENTARIOS', 'Anular registros de inventario'),
('DASHBOARD_VER', 'Ver Dashboard', 'DASHBOARDS', 'Acceso al tablero de indicadores generales'),
('CUENTA_COBRAR_VER', 'Ver Cuentas por Cobrar', 'REPORTES', 'Seguimiento de deudas de clientes'),
('CUENTA_PAGAR_VER', 'Ver Cuentas por Pagar', 'REPORTES', 'Seguimiento de deudas con proveedores'),
('PAGO_FACTURA_VER', 'Ver Pagos de Clientes', 'FACTURAS', 'Ver depósitos y cobros realizados'),
('PAGO_FACTURA_CREAR', 'Registrar Cobros', 'FACTURAS', 'Permite cobrar facturas a crédito'),
('PAGO_FACTURA_EDITAR', 'Editar Cobros', 'FACTURAS', 'Permite modificar cobros registrados'),
('PAGO_FACTURA_ELIMINAR', 'Eliminar Cobros', 'FACTURAS', 'Permite anular registros de cobro'),
('SUSCRIPCIONES_VER', 'Ver Suscripción', 'SUSCRIPCIONES', 'Ver estado del plan y pagos del sistema')
ON CONFLICT (codigo) DO UPDATE SET 
    nombre = EXCLUDED.nombre,
    modulo = EXCLUDED.modulo,
    descripcion = EXCLUDED.descripcion,
    updated_at = NOW();