from enum import Enum

class PermissionCodes(str, Enum):
    # Clientes
    CLIENTE_VER = "CLIENTE_VER"
    CLIENTE_CREAR = "CLIENTE_CREAR"
    CLIENTE_EDITAR = "CLIENTE_EDITAR"
    CLIENTE_ELIMINAR = "CLIENTE_ELIMINAR"
    CLIENTE_EXPORTAR = "CLIENTE_EXPORTAR"

    # Productos
    PRODUCTO_VER = "PRODUCTO_VER"
    PRODUCTO_CREAR = "PRODUCTO_CREAR"
    PRODUCTO_EDITAR = "PRODUCTO_EDITAR"
    PRODUCTO_ELIMINAR = "PRODUCTO_ELIMINAR"
    PRODUCTO_VER_COSTOS = "PRODUCTO_VER_COSTOS"

    # Proveedores
    PROVEEDOR_VER = "PROVEEDOR_VER"
    PROVEEDOR_CREAR = "PROVEEDOR_CREAR"
    PROVEEDOR_EDITAR = "PROVEEDOR_EDITAR"
    PROVEEDOR_ELIMINAR = "PROVEEDOR_ELIMINAR"

    # Facturas
    FACTURA_VER = "FACTURA_VER"
    FACTURA_VER_TODAS = "FACTURA_VER_TODAS"
    FACTURA_VER_PROPIAS = "FACTURA_VER_PROPIAS"
    FACTURA_CREAR = "FACTURA_CREAR"
    FACTURA_EDITAR = "FACTURA_EDITAR"
    FACTURA_ANULAR = "FACTURA_ANULAR"
    FACTURA_ELIMINAR = "FACTURA_ELIMINAR"
    FACTURA_ENVIAR_SRI = "FACTURA_ENVIAR_SRI"
    FACTURA_DESCARGAR_PDF = "FACTURA_DESCARGAR_PDF"
    FACTURA_ENVIAR_EMAIL = "FACTURA_ENVIAR_EMAIL"

    # Facturación Programada
    FACTURA_PROGRAMADA_VER = "FACTURA_PROGRAMADA_VER"
    FACTURA_PROGRAMADA_CREAR = "FACTURA_PROGRAMADA_CREAR"
    FACTURA_PROGRAMADA_EDITAR = "FACTURA_PROGRAMADA_EDITAR"
    FACTURA_PROGRAMADA_ELIMINAR = "FACTURA_PROGRAMADA_ELIMINAR"

    # Cuentas por Cobrar
    CUENTA_COBRAR_VER = "CUENTA_COBRAR_VER"
    CUENTA_COBRAR_CREAR = "CUENTA_COBRAR_CREAR"
    CUENTA_COBRAR_EDITAR = "CUENTA_COBRAR_EDITAR"
    CUENTA_COBRAR_ELIMINAR = "CUENTA_COBRAR_ELIMINAR"

    # Pagos
    PAGO_VER = "PAGO_VER"
    PAGO_CREAR = "PAGO_CREAR"
    PAGO_ANULAR = "PAGO_ANULAR"

    # Log Emision
    LOG_EMISION_VER = "LOG_EMISION_VER"

    # Reportes
    REPORTE_VER = "REPORTE_VER"
    REPORTE_EXPORTAR = "REPORTE_EXPORTAR"

    # Modulos
    MODULO_GESTIONAR = "MODULO_GESTIONAR"
    MODULO_VER = "MODULO_VER"

    # Empresa / Configuración
    EMPRESA_VER = "EMPRESA_VER"
    EMPRESA_EDITAR = "EMPRESA_EDITAR"
    CONFIG_SRI_EDITAR = "CONFIG_SRI_EDITAR"
    ESTABLECIMIENTO_GESTIONAR = "ESTABLECIMIENTO_GESTIONAR"

    # Usuarios
    USUARIO_GESTIONAR = "USUARIO_GESTIONAR"
    USUARIO_VER = "USUARIO_VER"
    USUARIO_CREAR = "USUARIO_CREAR"
    USUARIO_EDITAR = "USUARIO_EDITAR"
    USUARIO_ELIMINAR = "USUARIO_ELIMINAR"

    # Roles
    ROL_VER = "ROL_VER"
    ROL_CREAR = "ROL_CREAR"
    ROL_EDITAR = "ROL_EDITAR"
    ROL_ELIMINAR = "ROL_ELIMINAR"
    ROL_GESTIONAR_PERMISOS = "ROL_GESTIONAR_PERMISOS"

    # Permisos
    PERMISO_VER = "PERMISO_VER"
    PERMISO_CREAR = "PERMISO_CREAR"
    PERMISO_EDITAR = "PERMISO_EDITAR"
    PERMISO_ELIMINAR = "PERMISO_ELIMINAR"
