CREATE TABLE IF NOT EXISTS SUSCRIPCION (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    PRECIO_MENSUAL NUMERIC(10, 2),
    LIMITE_USUARIOS INT,
    LIMITE_FACTURAS_MENSUALES INT,
    LIMITE_ESTABLECIMIENTOS INT
);

CREATE TABLE IF NOT EXISTS MODULO_SUSCRIPCION (
    ID SERIAL PRIMARY KEY,
    FK_SUSCRIPCION INT NOT NULL REFERENCES SUSCRIPCION (ID),
    NOMBRE_MODULO VARCHAR(50) NOT NULL,
    CONSTRAINT UNIQUE_SUSCRIPCION_MODULO UNIQUE (FK_SUSCRIPCION, NOMBRE_MODULO)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    NUM_IDENTIFICACION VARCHAR(13) NOT NULL UNIQUE,
    CELULAR VARCHAR(13),
    DIRECCION VARCHAR(250),
    CORREO VARCHAR(100),
    TIPO_CLIENTE VARCHAR(10) CHECK (TIPO_CLIENTE IN ('NATURAL', 'JURIDICA'))
);

CREATE TABLE IF NOT EXISTS PROVEEDOR (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    RUC VARCHAR(13) NOT NULL UNIQUE,
    DIRECCION VARCHAR(250),
    TELEFONO VARCHAR(13)
);

CREATE TABLE IF NOT EXISTS PRODUCTO (
    ID SERIAL PRIMARY KEY,
    FK_PROVEEDOR INT REFERENCES PROVEEDOR (ID),
    NOMBRE_PRODUCTO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200),
    COSTO_UNITARIO NUMERIC(10, 2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    CODIGO_PRODUCTO VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TIPO_MOVIMIENTO (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL UNIQUE CHECK (NOMBRE IN ('COMPRA', 'VENTA', 'DEVOLUCION'))
);

CREATE TABLE IF NOT EXISTS UNIDAD_MEDIDA (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL UNIQUE CHECK (
        NOMBRE IN ('UNIDAD', 'CAJA', 'BULTO', 'KILO', 'METRO', 'LITRO')
    )
);

CREATE TABLE IF NOT EXISTS INVENTARIO (
    ID SERIAL PRIMARY KEY,
    FK_PRODUCTO INT NOT NULL REFERENCES PRODUCTO (ID),
    FK_TIPO_MOVIMIENTO INT NOT NULL REFERENCES TIPO_MOVIMIENTO (ID),
    FK_UNIDAD_MEDIDA INT NOT NULL REFERENCES UNIDAD_MEDIDA (ID),
    CANTIDAD INT NOT NULL,
    FECHA DATE NOT NULL DEFAULT CURRENT_DATE,
    ESTADO VARCHAR(15) NOT NULL CHECK (
        ESTADO IN ('DISPONIBLE', 'RESERVADO', 'DAÑADO', 'EN_TRANSITO')
    ),
    UBICACION_FISICA VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS FACTURACION_BASICA (
    ID SERIAL PRIMARY KEY,
    FK_CLIENTE INT NOT NULL REFERENCES CLIENTE (ID),
    NUM_FACTURA VARCHAR(50) UNIQUE,
    NOMBRE_EMISOR VARCHAR(50),
    NOMBRE_RECEPTOR VARCHAR(50),
    FECHA_EXPEDICION DATE NOT NULL DEFAULT CURRENT_DATE,
    FECHA_VENCIMIENTO DATE,
    DESCRIPCION VARCHAR(500),
    BASE_IMPONIBLE NUMERIC(10, 2) NOT NULL,
    IVA NUMERIC(10, 2) DEFAULT 0.00,
    DESCUENTOS NUMERIC(10, 2) DEFAULT 0.00,
    TOTAL NUMERIC(10, 2) NOT NULL,
    FORMA_PAGO VARCHAR(15) NOT NULL CHECK (
        FORMA_PAGO IN ('EFECTIVO', 'TRANSFERENCIA', 'TARJETA', 'CREDITO')
    ),
    COMENTARIOS VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS LIQUIDACION_COMPRA (
    ID SERIAL PRIMARY KEY,
    NOMBRE_PROVEEDOR VARCHAR(150),
    DIRECCION_PROVEEDOR VARCHAR(250),
    FECHA_EMISION DATE NOT NULL DEFAULT CURRENT_DATE,
    BASE_IMPONIBLE NUMERIC(10, 2) NOT NULL,
    IVA NUMERIC(10, 2) DEFAULT 0.00,
    RETENCIONES NUMERIC(10, 2) DEFAULT 0.00,
    VALOR_TOTAL NUMERIC(10, 2) NOT NULL,
    FORMA_PAGO VARCHAR(50) NOT NULL,
    PLAZO VARCHAR(20),
    NUMERACION_AUTORIZADA VARCHAR(15) UNIQUE,
    REEMBOLSOS_DE_GASTOS BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS DETALLE_LIQUIDACION_COMPRA (
    ID SERIAL PRIMARY KEY,
    FK_LIQUIDACION INT NOT NULL REFERENCES LIQUIDACION_COMPRA (ID),
    DESCRIPCION TEXT NOT NULL,
    CANTIDADES NUMERIC(10, 4) NOT NULL,
    VALOR_UNITARIO NUMERIC(10, 2) NOT NULL,
    VALOR_TOTAL_LINEA NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS RETENCION (
    ID SERIAL PRIMARY KEY,
    BASE_IMPONIBLE NUMERIC(10, 2) NOT NULL,
    PORCENTAJE_RETENCION NUMERIC(10, 2) NOT NULL,
    MOTIVO VARCHAR(500),
    MONTO_RETENIDO NUMERIC(10, 2) NOT NULL,
    IMPUESTOS_ADICIONALES NUMERIC(10, 2) DEFAULT 0.00,
    DETALLES_COMPROBANTE JSONB
);

CREATE TABLE IF NOT EXISTS GUIA_REMISION (
    ID SERIAL PRIMARY KEY,
    FK_FACTURA INT REFERENCES FACTURACION_BASICA (ID),
    FK_CLIENTE INT NOT NULL REFERENCES CLIENTE (ID),
    TIPO_IDENTIFICACION VARCHAR(10) NOT NULL CHECK (
        TIPO_IDENTIFICACION IN ('CEDULA', 'RUC', 'PASAPORTE')
    ),
    NUM_IDENTIFICACION VARCHAR(13) NOT NULL,
    DOMICILIO_FISCAL VARCHAR(50),
    LUGAR_ORIGEN VARCHAR(100) NOT NULL,
    LUGAR_DESTINO VARCHAR(100) NOT NULL,
    MOTIVO_TRASLADO VARCHAR(500) NOT NULL,
    MEDIO_TRANSPORTE VARCHAR(10) NOT NULL CHECK (
        MEDIO_TRANSPORTE IN ('CAMION', 'AVION', 'BARCO', 'MOTO')
    ),
    MERCANCIA_DESCRIPCION_DETALLADA VARCHAR(150),
    NUMERO_COMPROBANTE VARCHAR(50) UNIQUE,
    FECHA_EMISION DATE NOT NULL DEFAULT CURRENT_DATE,
    FECHA_VENCIMIENTO DATE,
    RUTA VARCHAR(500),
    ESTADO_DOCUMENTO VARCHAR(15) NOT NULL CHECK (
        ESTADO_DOCUMENTO IN ('EMITIDA', 'EN REVISION', 'CANCELADA', 'ENTREGADA')
    ),
    FIRMA_ELECTRONICA BYTEA
);

CREATE TABLE IF NOT EXISTS NOTA_CREDITO (
    ID SERIAL PRIMARY KEY,
    FK_FACTURA_BASICA INT NOT NULL REFERENCES FACTURACION_BASICA (ID),
    NOMBRE_CLIENTE VARCHAR(100),
    DIRECCION VARCHAR(250),
    NUM_IDENTIFICACION VARCHAR(13),
    FECHA_EMISION DATE NOT NULL DEFAULT CURRENT_DATE,
    MOTIVO VARCHAR(500) NOT NULL,
    IMPORTE_TOTAL NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS DETALLE_NOTA_CREDITO (
    ID SERIAL PRIMARY KEY,
    FK_NOTA_CREDITO INT NOT NULL REFERENCES NOTA_CREDITO (ID),
    FK_PRODUCTO INT REFERENCES PRODUCTO (ID),
    CANTIDAD INT NOT NULL,
    VALOR_AJUSTADO NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTABILIDAD (
    ID SERIAL PRIMARY KEY,
    FECHA_TRANSACCION DATE NOT NULL DEFAULT CURRENT_DATE,
    DESCRIPCION TEXT,
    NUM_IDENTIFICACION VARCHAR(13),
    MONTO_DEBE NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    MONTO_HABER NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    FK_FACTURA INT REFERENCES FACTURACION_BASICA (ID),
    FK_LIQUIDACION INT REFERENCES LIQUIDACION_COMPRA (ID)
);

CREATE TABLE IF NOT EXISTS DETALLE_FACTURA (
    ID SERIAL PRIMARY KEY,
    FK_FACTURA_BASICA INT NOT NULL REFERENCES FACTURACION_BASICA (ID),
    FK_PRODUCTO INT NOT NULL REFERENCES PRODUCTO (ID),
    CANTIDAD INT NOT NULL,
    VALOR_UNITARIO NUMERIC(10, 2) NOT NULL,
    SUBTOTAL NUMERIC(10, 2) NOT NULL,
    UNIQUE (FK_FACTURA_BASICA, FK_PRODUCTO)
);

CREATE TABLE IF NOT EXISTS FACTURACION_PROGRAMADA (
    ID SERIAL PRIMARY KEY,
    FK_CLIENTE INT NOT NULL REFERENCES CLIENTE (ID),
    FK_FACTURA_BASICA INT NOT NULL REFERENCES FACTURACION_BASICA (ID),
    FRECUENCIA VARCHAR(15) NOT NULL CHECK (FRECUENCIA IN ('MENSUAL', 'TRIMESTRAL', 'ANUAL')),
    ESTADO VARCHAR(15) NOT NULL CHECK (ESTADO IN ('ACTIVA', 'PAUSADA', 'FINALIZADA')),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE
);

CREATE TABLE IF NOT EXISTS REPORTE_BASICO (
    ID SERIAL PRIMARY KEY,
    FK_FACTURA_BASICA INT REFERENCES FACTURACION_BASICA (ID),
    FK_RETENCION INT REFERENCES RETENCION (ID),
    FK_NOTA_CREDITO INT REFERENCES NOTA_CREDITO (ID),
    NOMBRE_EMISOR VARCHAR(50),
    NOMBRE_CLIENTE VARCHAR(50),
    DIRECCION_EMISOR VARCHAR(100),
    DIRECCION_CLIENTE VARCHAR(100),
    ABONO_REALIZADO NUMERIC(10, 2),
    FECHA_ABONO DATE,
    SALDO_PENDIENTE NUMERIC(10, 2),
    NUM_AUTORIZACION VARCHAR(50),
    FIRMA_ELECTRONICA BYTEA
);

CREATE TABLE IF NOT EXISTS REPORTE_AVANZADO (
    ID SERIAL PRIMARY KEY,
    FK_NOTA_CREDITO INT REFERENCES NOTA_CREDITO (ID),
    CARGOS_DETALLADOS JSONB,
    TRANSACCIONES_DETALLADAS JSONB,
    INFORMACION_ADICIONAL JSONB
);
