from uuid import UUID
from datetime import date, datetime
from decimal import Decimal
from typing import Optional, List
from pydantic import BaseModel, Field

# Base Model
class FacturaBase(BaseModel):
    establecimiento_id: UUID
    punto_emision_id: UUID
    cliente_id: UUID
    facturacion_programada_id: Optional[UUID] = None
    
    fecha_emision: date
    fecha_vencimiento: Optional[date] = None
    
    subtotal_sin_iva: Decimal = Field(default=Decimal('0.00'), ge=0)
    subtotal_con_iva: Decimal = Field(default=Decimal('0.00'), ge=0)
    iva: Decimal = Field(default=Decimal('0.00'), ge=0)
    descuento: Decimal = Field(default=Decimal('0.00'), ge=0)
    propina: Decimal = Field(default=Decimal('0.00'), ge=0)
    # Total is usually calculated, but user might send it for validation? 
    # Or should be calculated in backend. 
    # Schema says NOT NULL. Let's require it or calculate it.
    # Usually frontend calculates and backend validates.
    total: Decimal = Field(..., ge=0)
    
    origen: Optional[str] = None
    observaciones: Optional[str] = None

# Create Input (API)
class FacturaCreateInput(FacturaBase):
    empresa_id: Optional[UUID] = None # Superadmin only, optional for logic
    usuario_id: Optional[UUID] = None # Superadmin only, optional for logic
    
    # Note: numero_factura and clave_acceso are usually generated by Backend/SRI logic.
    # We won't require them in Input.

# Internal Create (Repo)
class FacturaCreate(FacturaBase):
    empresa_id: UUID
    usuario_id: UUID
    numero_factura: str
    clave_acceso: Optional[str] = None
    estado: str = 'EMITIDA'
    estado_pago: str = 'PENDIENTE'

# Update
class FacturaUpdate(BaseModel):
    # Usually Invoices are immutable once emitted/SRI approved. 
    # But maybe for draft or specific fields like 'observaciones' or 'estado_pago'.
    estado_pago: Optional[str] = None
    observaciones: Optional[str] = None
    
    # Allow updating common fields if needed (e.g. implementation error correction)
    fecha_emision: Optional[date] = None
    fecha_vencimiento: Optional[date] = None
    subtotal_sin_iva: Optional[Decimal] = Field(None, ge=0)
    subtotal_con_iva: Optional[Decimal] = Field(None, ge=0)
    iva: Optional[Decimal] = Field(None, ge=0)
    descuento: Optional[Decimal] = Field(None, ge=0)
    propina: Optional[Decimal] = Field(None, ge=0)
    total: Optional[Decimal] = Field(None, ge=0)
    origen: Optional[str] = None
    estado: Optional[str] = None
    facturacion_programada_id: Optional[UUID] = None

# Read
class FacturaRead(FacturaBase):
    id: UUID
    empresa_id: UUID
    usuario_id: UUID
    numero_factura: str
    clave_acceso: Optional[str] = None
    estado: str
    estado_pago: str
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
