from enum import Enum

class ModuloPermisos(str, Enum):
    CLIENTES = "CLIENTES"
    PRODUCTOS = "PRODUCTOS"
    FACTURAS = "FACTURAS"
    REPORTES = "REPORTES"
    CONFIGURACION = "CONFIGURACION"
    GASTOS = "GASTOS"
    INVENTARIOS = "INVENTARIOS"
    PROVEEDORES = "PROVEEDORES"
    ESTABLECIMIENTOS = "ESTABLECIMIENTOS"
    DASHBOARDS = "DASHBOARDS"
    USUARIOS_EMPRESA = "USUARIOS_EMPRESA"
    ROLES = "ROLES"
    SUSCRIPCIONES = "SUSCRIPCIONES"
    SUPERADMIN = "SUPERADMIN"

