from enum import Enum

class ModuloPermisos(str, Enum):
    CLIENTES = "CLIENTES"
    PRODUCTOS = "PRODUCTOS"
    FACTURAS = "FACTURAS"
    REPORTES = "REPORTES"
    CONFIGURACION = "CONFIGURACION"
    GASTOS = "GASTOS"
    INVENTARIOS = "INVENTARIOS"
    PROVEEDORES = "PROVEEDORES"
    ESTABLECIMIENTOS = "ESTABLECIMIENTOS"
    COMISIONES = "COMISIONES"
    DASHBOARDS = "DASHBOARDS"
    VENDEDORES = "VENDEDORES"
    SUSCRIPCIONES = "SUSCRIPCIONES"
    SUPERADMIN = "SUPERADMIN"

