class PermissionCodes:
    # --- MÓDULO: CLIENTES ---
    CLIENTES_VER = "CLIENTES_VER"
    CLIENTES_CREAR = "CLIENTES_CREAR"
    CLIENTES_EDITAR = "CLIENTES_EDITAR"
    CLIENTES_ELIMINAR = "CLIENTES_ELIMINAR"
    CLIENTES_EXPORTAR = "CLIENTES_EXPORTAR"

    # --- MÓDULO: PRODUCTOS ---
    PRODUCTOS_VER = "PRODUCTOS_VER"
    PRODUCTOS_CREAR = "PRODUCTOS_CREAR"
    PRODUCTOS_EDITAR = "PRODUCTOS_EDITAR"
    PRODUCTOS_ELIMINAR = "PRODUCTOS_ELIMINAR"
    PRODUCTOS_VER_COSTOS = "PRODUCTOS_VER_COSTOS"
    
    # --- MÓDULO: FACTURAS ---
    FACTURAS_VER_TODAS = "FACTURAS_VER_TODAS"
    FACTURAS_VER_PROPIAS = "FACTURAS_VER_PROPIAS"
    FACTURAS_CREAR = "FACTURAS_CREAR"
    FACTURAS_EDITAR = "FACTURAS_EDITAR"
    FACTURAS_ANULAR = "FACTURAS_ANULAR"
    FACTURAS_ENVIAR_SRI = "FACTURAS_ENVIAR_SRI"
    FACTURAS_DESCARGAR_PDF = "FACTURAS_DESCARGAR_PDF"
    FACTURAS_ENVIAR_EMAIL = "FACTURAS_ENVIAR_EMAIL"

    # --- MÓDULO: FACTURACIÓN PROGRAMADA ---
    FACTURA_PROGRAMADA_VER_PROPIAS = "FACTURA_PROGRAMADA_VER_PROPIAS"
    FACTURA_PROGRAMADA_VER = "FACTURA_PROGRAMADA_VER"
    FACTURA_PROGRAMADA_CREAR = "FACTURA_PROGRAMADA_CREAR"
    FACTURA_PROGRAMADA_EDITAR = "FACTURA_PROGRAMADA_EDITAR"
    FACTURA_PROGRAMADA_ELIMINAR = "FACTURA_PROGRAMADA_ELIMINAR"
    
    # --- MÓDULO: REPORTES ---
    REPORTES_VER = "REPORTES_VER"
    REPORTES_GENERAR = "REPORTES_GENERAR"
    REPORTES_EXPORTAR = "REPORTES_EXPORTAR"

    # --- MÓDULO: CONFIGURACIÓN ---
    CONFIG_EMPRESA = "CONFIG_EMPRESA"
    CONFIG_SRI = "CONFIG_SRI"
    CONFIG_ROLES = "CONFIG_ROLES"

    # --- MODULO: USUARIOS ---
    USUARIOS_VER = "USUARIOS_VER"
    USUARIOS_CREAR = "USUARIOS_CREAR"
    USUARIOS_EDITAR = "USUARIOS_EDITAR"
    USUARIOS_ELIMINAR = "USUARIOS_ELIMINAR"
    
    # --- MÓDULO: ESTABLECIMIENTOS Y PUNTOS ---
    ESTABLECIMIENTO_GESTIONAR = "ESTABLECIMIENTO_GESTIONAR"
    PUNTO_EMISION_GESTIONAR = "PUNTO_EMISION_GESTIONAR"
    
    # --- MÓDULO: PROVEEDORES ---
    PROVEEDOR_VER = "PROVEEDOR_VER"
    PROVEEDOR_CREAR = "PROVEEDOR_CREAR"
    PROVEEDOR_EDITAR = "PROVEEDOR_EDITAR"
    PROVEEDOR_ELIMINAR = "PROVEEDOR_ELIMINAR"
    
    # --- MÓDULO: GASTOS ---
    GASTOS_VER = "GASTOS_VER"
    GASTOS_CREAR = "GASTOS_CREAR"
    GASTOS_EDITAR = "GASTOS_EDITAR"
    GASTOS_ELIMINAR = "GASTOS_ELIMINAR"
    # Categorias de Gastos
    CATEGORIA_GASTO_VER = "CATEGORIA_GASTO_VER"
    CATEGORIA_GASTO_CREAR = "CATEGORIA_GASTO_CREAR"
    CATEGORIA_GASTO_EDITAR = "CATEGORIA_GASTO_EDITAR"
    CATEGORIA_GASTO_ELIMINAR = "CATEGORIA_GASTO_ELIMINAR"
    # Pagos de Gastos
    PAGO_GASTO_VER = "PAGO_GASTO_VER"
    PAGO_GASTO_CREAR = "PAGO_GASTO_CREAR"
    PAGO_GASTO_EDITAR = "PAGO_GASTO_EDITAR"
    PAGO_GASTO_ELIMINAR = "PAGO_GASTO_ELIMINAR"

    # --- OTROS ---
    DASHBOARD_VER = "DASHBOARD_VER"
    
    # Cuentas por Cobrar/Pagar
    CUENTA_COBRAR_VER = "CUENTA_COBRAR_VER"

    # Pagos de Facturas (Cuentas por Cobrar)
    PAGO_FACTURA_VER = "PAGO_FACTURA_VER"
    PAGO_FACTURA_CREAR = "PAGO_FACTURA_CREAR"
    PAGO_FACTURA_EDITAR = "PAGO_FACTURA_EDITAR"
    PAGO_FACTURA_ELIMINAR = "PAGO_FACTURA_ELIMINAR"
