class PermissionCodes:
    # --- MÓDULO: CLIENTES ---
    CLIENTES_VER = "CLIENTES_VER"
    CLIENTES_CREAR = "CLIENTES_CREAR"
    CLIENTES_EDITAR = "CLIENTES_EDITAR"
    CLIENTES_ELIMINAR = "CLIENTES_ELIMINAR"
    CLIENTES_EXPORTAR = "CLIENTES_EXPORTAR"

    # --- MÓDULO: PRODUCTOS ---
    PRODUCTOS_VER = "PRODUCTOS_VER"
    PRODUCTOS_CREAR = "PRODUCTOS_CREAR"
    PRODUCTOS_EDITAR = "PRODUCTOS_EDITAR"
    PRODUCTOS_ELIMINAR = "PRODUCTOS_ELIMINAR"
    PRODUCTOS_VER_COSTOS = "PRODUCTOS_VER_COSTOS"
    
    # Compatibilidad
    PRODUCTO_VER = "PRODUCTOS_VER"
    PRODUCTO_CREAR = "PRODUCTOS_CREAR"
    PRODUCTO_EDITAR = "PRODUCTOS_EDITAR"
    PRODUCTO_ELIMINAR = "PRODUCTOS_ELIMINAR"

    # --- MÓDULO: FACTURAS ---
    FACTURAS_VER_TODAS = "FACTURAS_VER_TODAS"
    FACTURAS_VER_PROPIAS = "FACTURAS_VER_PROPIAS"
    FACTURAS_CREAR = "FACTURAS_CREAR"
    FACTURAS_EDITAR = "FACTURAS_EDITAR"
    FACTURAS_ANULAR = "FACTURAS_ANULAR"
    FACTURAS_ENVIAR_SRI = "FACTURAS_ENVIAR_SRI"
    FACTURAS_DESCARGAR_PDF = "FACTURAS_DESCARGAR_PDF"
    FACTURAS_ENVIAR_EMAIL = "FACTURAS_ENVIAR_EMAIL"
    
    # Compatibilidad
    FACTURA_VER = "FACTURAS_VER_TODAS"
    FACTURA_CREAR = "FACTURAS_CREAR"
    FACTURA_EDITAR = "FACTURAS_EDITAR"
    FACTURA_ANULAR = "FACTURAS_ANULAR"
    FACTURA_ELIMINAR = "FACTURAS_ANULAR"
    FACTURA_ENVIAR_SRI = "FACTURAS_ENVIAR_SRI"

    # --- MÓDULO: REPORTES ---
    REPORTES_VER = "REPORTES_VER"
    REPORTES_EXPORTAR = "REPORTES_EXPORTAR"
    REPORTE_VER = "REPORTES_VER"
    REPORTE_EXPORTAR = "REPORTES_EXPORTAR"
    
    # Granularidad por área
    REPORTE_FINANCIERO_VER = "REPORTE_FINANCIERO_VER"
    REPORTE_VENTAS_VER = "REPORTE_VENTAS_VER"
    REPORTE_INVENTARIO_VER = "REPORTE_INVENTARIO_VER"

    # --- MÓDULO: CONFIGURACIÓN ---
    CONFIG_EMPRESA = "CONFIG_EMPRESA"
    CONFIG_SRI = "CONFIG_SRI"
    CONFIG_USUARIOS = "CONFIG_USUARIOS"
    CONFIG_ROLES = "CONFIG_ROLES"
    CONFIG_ESTABLECIMIENTOS = "CONFIG_ESTABLECIMIENTOS"
    CONFIG_MODULOS = "MODULOS_GESTIONAR"
    
    # Granularidad Usuarios/Roles
    USUARIOS_VER = "USUARIOS_VER"
    USUARIOS_GESTIONAR = "USUARIOS_GESTIONAR"
    ROLES_GESTIONAR = "CONFIG_ROLES"
    MODULOS_GESTIONAR = "MODULOS_GESTIONAR"
    
    PERMISO_VER = "CONFIG_ROLES"
    CONFIG_EMPRESA_DETALLES = "CONFIG_EMPRESA"
    
    # --- MÓDULO: ESTABLECIMIENTOS Y PUNTOS ---
    ESTABLECIMIENTO_VER = "ESTABLECIMIENTO_VER"
    ESTABLECIMIENTO_CREAR = "ESTABLECIMIENTO_GESTIONAR"
    ESTABLECIMIENTO_EDITAR = "ESTABLECIMIENTO_GESTIONAR"
    ESTABLECIMIENTO_ELIMINAR = "ESTABLECIMIENTO_GESTIONAR"
    
    PUNTO_EMISION_VER = "PUNTO_EMISION_VER"
    PUNTO_EMISION_CREAR = "PUNTO_EMISION_GESTIONAR"
    PUNTO_EMISION_EDITAR = "PUNTO_EMISION_GESTIONAR"
    PUNTO_EMISION_ELIMINAR = "PUNTO_EMISION_GESTIONAR"
    
    # --- MÓDULO: PROVEEDORES ---
    PROVEEDOR_VER = "PROVEEDOR_VER"
    PROVEEDOR_CREAR = "PROVEEDOR_CREAR"
    PROVEEDOR_EDITAR = "PROVEEDOR_EDITAR"
    PROVEEDOR_ELIMINAR = "PROVEEDOR_ELIMINAR"
    
    # --- MÓDULO: FORMAS DE PAGO ---
    FORMA_PAGO_VER = "FORMA_PAGO_VER"
    FORMA_PAGO_CREAR = "FORMA_PAGO_GESTIONAR"
    FORMA_PAGO_EDITAR = "FORMA_PAGO_GESTIONAR"
    FORMA_PAGO_ELIMINAR = "FORMA_PAGO_GESTIONAR"
    
    # --- MÓDULO: GASTOS ---
    GASTOS_VER = "GASTOS_VER"
    GASTOS_CREAR = "GASTOS_CREAR"
    GASTOS_EDITAR = "GASTOS_EDITAR"
    GASTOS_ELIMINAR = "GASTOS_ELIMINAR"
    CATEGORIA_GASTO_VER = "CATEGORIA_GASTO_VER"
    CATEGORIA_GASTO_CREAR = "CATEGORIA_GASTO_CREAR"
    CATEGORIA_GASTO_EDITAR = "CATEGORIA_GASTO_EDITAR"
    CATEGORIA_GASTO_ELIMINAR = "CATEGORIA_GASTO_ELIMINAR"
    PAGO_GASTO_VER = "PAGO_GASTO_VER"
    PAGO_GASTO_CREAR = "PAGO_GASTO_CREAR"
    PAGO_GASTO_EDITAR = "PAGO_GASTO_EDITAR"
    PAGO_GASTO_ELIMINAR = "PAGO_GASTO_ELIMINAR"

    # --- MÓDULO: INVENTARIOS ---
    INVENTARIO_VER = "INVENTARIO_VER"
    INVENTARIO_CREAR = "INVENTARIO_CREAR"
    INVENTARIO_EDITAR = "INVENTARIO_EDITAR"
    INVENTARIO_ELIMINAR = "INVENTARIO_ELIMINAR"
    
    # Unidades de medida
    UNIDAD_MEDIDA_VER = "UNIDAD_MEDIDA_VER"
    UNIDAD_MEDIDA_CREAR = "UNIDAD_MEDIDA_GESTIONAR"
    UNIDAD_MEDIDA_EDITAR = "UNIDAD_MEDIDA_GESTIONAR"
    UNIDAD_MEDIDA_ELIMINAR = "UNIDAD_MEDIDA_GESTIONAR"
    
    # Tipos de movimiento
    TIPO_MOVIMIENTO_VER = "TIPO_MOVIMIENTO_VER"
    TIPO_MOVIMIENTO_CREAR = "TIPO_MOVIMIENTO_GESTIONAR"
    TIPO_MOVIMIENTO_EDITAR = "TIPO_MOVIMIENTO_GESTIONAR"
    TIPO_MOVIMIENTO_ELIMINAR = "TIPO_MOVIMIENTO_GESTIONAR"

    # --- OTROS ---
    NOTIFICACION_LISTAR = "NOTIFICACION_LISTAR"
    NOTIFICACION_LEER = "NOTIFICACION_LEER"
    NOTIFICACION_SISTEMA_CREAR = "NOTIFICACION_SISTEMA_CREAR"
    LOG_EMISION_VER = "LOG_EMISION_VER"
    DASHBOARD_VER = "DASHBOARD_VER"
    
    # Cuentas por Cobrar/Pagar
    CUENTA_COBRAR_VER = "CUENTA_COBRAR_VER"
    CUENTA_COBRAR_CREAR = "CUENTA_COBRAR_CREAR"
    CUENTA_COBRAR_EDITAR = "CUENTA_COBRAR_EDITAR"
    CUENTA_COBRAR_ELIMINAR = "CUENTA_COBRAR_ELIMINAR"
    CUENTA_PAGAR_VER = "CUENTA_PAGAR_VER"
    CUENTA_PAGAR_CREAR = "CUENTA_PAGAR_CREAR"
    CUENTA_PAGAR_EDITAR = "CUENTA_PAGAR_EDITAR"
    CUENTA_PAGAR_ELIMINAR = "CUENTA_PAGAR_ELIMINAR"
    
    # Reportes Generados e Históricos
    REPORTE_GENERADO_VER = "REPORTE_GENERADO_VER"
    REPORTE_GENERADO_ELIMINAR = "REPORTE_GENERADO_ELIMINAR"
    REPORTE_GENERADO_CREAR = "REPORTES_EXPORTAR" 
    
    # Suscripciones
    SUSCRIPCIONES_VER = "SUSCRIPCIONES_VER"
    SUSCRIPCIONES_GESTIONAR = "SUSCRIPCIONES_GESTIONAR"
    
    # Comisiones
    COMISIONES_VER = "COMISIONES_VER"
    COMISIONES_GESTIONAR = "COMISIONES_GESTIONAR"
    
    # Vendores / Perfil
    VENDEDORES_VER = "VENDEDORES_VER"
    VENDEDORES_GESTIONAR = "VENDEDORES_GESTIONAR"

    # Facturación Programada
    FACTURA_PROGRAMADA_VER = "FACTURAS_VER_TODAS"
    FACTURA_PROGRAMADA_CREAR = "FACTURAS_CREAR"
    FACTURA_PROGRAMADA_EDITAR = "FACTURAS_EDITAR"
    FACTURA_PROGRAMADA_ELIMINAR = "FACTURAS_ANULAR"

    # Pagos (Cuentas por cobrar)
    PAGO_VER = "CUENTA_COBRAR_VER"
    PAGO_CREAR = "CUENTA_COBRAR_CREAR"
