class ErrorCodes:
    # AUTH
    AUTH_CREDENTIALS_INVALID = "AUTH_001"
    AUTH_USER_NOT_FOUND = "AUTH_002"
    AUTH_PASSWORD_MISMATCH = "AUTH_003"
    AUTH_TOKEN_INVALID = "AUTH_004"
    AUTH_TOKEN_EXPIRED = "AUTH_005"
    AUTH_INACTIVE_USER = "AUTH_006"
    AUTH_SESSION_EXPIRED = "AUTH_007"
    AUTH_SESSION_ALREADY_ACTIVE = "AUTH_008"
    
    # PERMISSIONS
    PERM_FORBIDDEN = "PERM_001"
    PERM_INSUFFICIENT_ROLE = "PERM_002"
    
    # DATABASE
    DB_CONNECTION_ERROR = "DB_001"
    DB_QUERY_ERROR = "DB_002"
    DB_CONSTRAINT_VIOLATION = "DB_003"
    DB_NOT_FOUND = "DB_004"
    
    # VALIDATION
    VAL_INVALID_INPUT = "VAL_001"
    VAL_MISSING_FIELD = "VAL_002"
    VAL_INVALID_FORMAT = "VAL_003"
    
    # BUSINESS LOGIC
    BUS_RULE_VIOLATION = "BUS_001"
    BUS_RESOURCE_STATE = "BUS_002"
    
    # ROLES
    ROLE_NOT_FOUND = "ROLE_001"
    ROLE_SYSTEM_PROTECTED = "ROLE_002"
    ROLE_UPDATE_ERROR = "ROLE_003"
    ROLE_DELETE_ERROR = "ROLE_004"
    ROLE_PERMISSION_ERROR = "ROLE_005"

    # SYSTEM
    SYS_INTERNAL_ERROR = "SYS_001"
    SYS_TIMEOUT = "SYS_002"
