
db_codes = """
CLIENTES_VER
CLIENTES_CREAR
CLIENTES_EDITAR
CLIENTES_ELIMINAR
CLIENTES_EXPORTAR
PRODUCTOS_VER
PRODUCTOS_CREAR
PRODUCTOS_EDITAR
PRODUCTOS_ELIMINAR
PRODUCTOS_VER_COSTOS
FACTURAS_VER_TODAS
FACTURAS_VER_PROPIAS
FACTURAS_CREAR
FACTURAS_EDITAR
FACTURAS_ANULAR
FACTURAS_ENVIAR_SRI
FACTURAS_DESCARGAR_PDF
FACTURAS_ENVIAR_EMAIL
REPORTES_VER
REPORTES_EXPORTAR
CONFIG_EMPRESA
CONFIG_SRI
CONFIG_USUARIOS
CONFIG_ROLES
CONFIG_ESTABLECIMIENTOS
ESTABLECIMIENTO_VER
ESTABLECIMIENTO_GESTIONAR
PUNTO_EMISION_VER
PUNTO_EMISION_GESTIONAR
PROVEEDOR_VER
PROVEEDOR_CREAR
PROVEEDOR_EDITAR
PROVEEDOR_ELIMINAR
FORMA_PAGO_VER
FORMA_PAGO_GESTIONAR
GASTOS_VER
GASTOS_CREAR
GASTOS_EDITAR
GASTOS_ELIMINAR
CATEGORIA_GASTO_VER
CATEGORIA_GASTO_CREAR
CATEGORIA_GASTO_EDITAR
CATEGORIA_GASTO_ELIMINAR
PAGO_GASTO_VER
PAGO_GASTO_CREAR
PAGO_GASTO_EDITAR
PAGO_GASTO_ELIMINAR
INVENTARIO_VER
INVENTARIO_CREAR
INVENTARIO_EDITAR
INVENTARIO_ELIMINAR
UNIDAD_MEDIDA_VER
UNIDAD_MEDIDA_GESTIONAR
TIPO_MOVIMIENTO_VER
TIPO_MOVIMIENTO_GESTIONAR
REPORTE_GENERADO_VER
REPORTE_GENERADO_ELIMINAR
REPORTE_FINANCIERO_VER
REPORTE_VENTAS_VER
REPORTE_INVENTARIO_VER
USUARIOS_VER
USUARIOS_GESTIONAR
ROLES_GESTIONAR
MODULOS_GESTIONAR
VENDEDORES_VER
VENDEDORES_GESTIONAR
SUSCRIPCIONES_VER
SUSCRIPCIONES_GESTIONAR
COMISIONES_VER
COMISIONES_GESTIONAR
CUENTA_COBRAR_VER
CUENTA_COBRAR_CREAR
CUENTA_COBRAR_EDITAR
CUENTA_COBRAR_ELIMINAR
CUENTA_PAGAR_VER
CUENTA_PAGAR_CREAR
CUENTA_PAGAR_EDITAR
CUENTA_PAGAR_ELIMINAR
DASHBOARD_VER
NOTIFICACION_LISTAR
NOTIFICACION_LEER
NOTIFICACION_SISTEMA_CREAR
LOG_EMISION_VER
""".strip().split()

import re

with open(r'c:\Users\fredy\Documents\Practicas\FacturacionProyecto\backend\src\constants\empresa_permisos\codes.py', 'r') as f:
    content = f.read()

# Extract all string values assigned to constants
# Matches things like: SOME_NAME = "SOME_VALUE"
file_values = set(re.findall(r'=\s*"([^"]+)"', content))

db_set = set(db_codes)

missing = sorted(list(db_set - file_values))
extra = sorted(list(file_values - db_set))

print("=== FALTAN EN codes.py (Están en DB) ===")
for m in missing:
    print(f"- {m}")

print("\n=== ESTÁN DE MÁS EN codes.py (No están en DB) ===")
for e in extra:
    print(f"- {e}")
