
db_codes = """
CLIENTES_VER
CLIENTES_CREAR
CLIENTES_EDITAR
CLIENTES_ELIMINAR
CLIENTES_EXPORTAR
PRODUCTOS_VER
PRODUCTOS_CREAR
PRODUCTOS_EDITAR
PRODUCTOS_ELIMINAR
PRODUCTOS_VER_COSTOS
FACTURAS_VER_TODAS
FACTURAS_VER_PROPIAS
FACTURAS_CREAR
FACTURAS_EDITAR
FACTURAS_ANULAR
FACTURAS_ENVIAR_SRI
FACTURAS_DESCARGAR_PDF
FACTURAS_ENVIAR_EMAIL
REPORTES_VER
REPORTES_EXPORTAR
CONFIG_EMPRESA
CONFIG_SRI
CONFIG_USUARIOS
CONFIG_ROLES
CONFIG_ESTABLECIMIENTOS
ESTABLECIMIENTO_VER
ESTABLECIMIENTO_GESTIONAR
PUNTO_EMISION_VER
PUNTO_EMISION_GESTIONAR
PROVEEDOR_VER
PROVEEDOR_CREAR
PROVEEDOR_EDITAR
PROVEEDOR_ELIMINAR
GASTOS_VER
GASTOS_CREAR
GASTOS_EDITAR
GASTOS_ELIMINAR
CATEGORIA_GASTO_VER
CATEGORIA_GASTO_CREAR
CATEGORIA_GASTO_EDITAR
CATEGORIA_GASTO_ELIMINAR
PAGO_GASTO_VER
PAGO_GASTO_CREAR
PAGO_GASTO_EDITAR
PAGO_GASTO_ELIMINAR
INVENTARIO_VER
INVENTARIO_CREAR
INVENTARIO_EDITAR
INVENTARIO_ELIMINAR
USUARIOS_VER
USUARIOS_GESTIONAR
MODULOS_GESTIONAR
VENDEDORES_VER
VENDEDORES_GESTIONAR
SUSCRIPCIONES_VER
CUENTA_COBRAR_VER
CUENTA_PAGAR_VER
DASHBOARD_VER
""".strip().split()

import re

with open(r'c:\Users\fredy\Documents\Practicas\FacturacionProyecto\backend\src\constants\empresa_permisos\codes.py', 'r') as f:
    content = f.read()

# Extract all string values assigned to constants in codes.py
codes_in_file = set(re.findall(r'=\s*"([^"]+)"', content))
db_set = set(db_codes)

# What is in codes.py but NOT in DB?
missing_in_db = sorted(list(codes_in_file - db_set))

print("=== EN codes.py PERO NO EN DB ===")
for m in missing_in_db:
    print(f"- {m}")
